### ISSUE TITLE
Integrate Giovanni for Apple Watch

### ISSUE THREAD

**Issue by gklka** [Provenance-Emu/Provenance#1102]
https://github.com/gabrieloc/GIOVANNI – Giovanni is a nice little GameBoy emulator for the Apple Watch. Since Provenance always had strong iOS device support, I think adding an Apple Watch GB emulator would be very welcomed.

You can ask – what is it for? Of course just for fun. Tetris is quite playable on the toilet tho. ;)

**Comment by jasarien** [comment]
I’m gonna go with.. no 🤣

**Comment by JoeMatt** [comment]
This is out of scope of what Provenance intends to have as features.

Some Apple Watch ideas have been documented - controller input, library browsing etc.

Provenance is working on a bundle format for exporting/importing save states across various cores, and a Peer to Peer cross platform method to advertise and transfer them. 

When we get that, and since it'll be open source, other emulators are welcome to incorporate this future SDK to transfer ROMs and save data - but we don't need to bring every emulator under the sun directly into Provenance.
