### ISSUE TITLE
Utilize new Mode 7 upscaling tech.

### ISSUE THREAD

**Issue by MysticalOS** [Provenance-Emu/Provenance#1107]
https://arstechnica.com/gaming/2019/04/hd-emulation-mod-makes-mode-7-snes-games-look-like-new/ has recently done an article on a new technique that deserves it's own ticket. It's not just a filter request or some kind of post processing at all. It's actually a form of pre processing of upscaling BEFORE textures are even processed by Mode 7, to greatly reduce distortion and improve graphics quality a ton.

Byuu has been doing a series of tweets on it too and since he's working on getting it in bsnes core, I assume there should at least be some possibility that the snes core in provenance can be updated to take advantage of these new methods.

**Comment by MysticalOS** [comment]
https://www.reddit.com/r/emulation/comments/bdltmo/hd_mode_7_mod_for_bsnes_v1071_beta_1/

**Comment by JoeMatt** [comment]
We don't use bsnes, and this is a mod of bsnes at that. I follow their development, i'm aware of the progress. There is no one working on porting BSNES, and it's not planned, but if someone does it, they can make a Work in Progress Pull Request ticket. Closing this ticket since it doens't have any current scope and I'm trying to not clutter actual tickets with tickets that have no plans on ever being done.
