### ISSUE TITLE
Lost save state

### ISSUE THREAD

**Issue by donmande7** [Provenance-Emu/Provenance#1108]
1. After selecting "Refresh Game Library", the Save States are gone.
2. When i connect the iPhone with my Mac, i can find the Save States including the .Png's, so i made a backup.
3. After inserting the backup, the problem still exists (no save state)

#

#### APP VERSION
- [x] 1.5 *beta*
- [ ] 1.4

#### APP SOURCE
- [ ] Provenance-Emu GitHub  *&nbsp;(Official)*
- [x ] Other  *builtstore*

#### INSTALLED BY 
- [ x] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*

#### PLATFORM
- [x ] iPhone
- [ ] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [x ] 12.x
- [ ] 11.x
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by JoeMatt** [comment]
Are you using iCloud sync of saves?

**Comment by donmande7** [comment]
No, i only use the import/export function in Provenance

**Comment by L1ebermann** [comment]
Hey, dude. I also lost my saves a week ago, but I found a way to recover my saves, and I have a solution for this trouble. I don't speak english well, but I'll try to explain.

First, you need to download your save stats to your PC. I noticed that actual name of these files change when you download it, because Windows changes file name according to its standarts. Example:

![Screenshot_2](https://user-images.githubusercontent.com/50751114/57949301-afe2c480-78ec-11e9-9676-ff8b70255f57.png)

Then, what I did is cleaned all save states I had in folder Iphone\Save states\[%Game]. 
Now you are going to your game, and do ONE save state. Then you are going to your save state folder and see 2 files: one containing .png and the other one is .svs; What you do now is : COPY both .svs and .png files from your PC with matching numbers: 

![Untitled](https://user-images.githubusercontent.com/50751114/57949581-81b1b480-78ed-11e9-8171-b91125bea9e0.png)


Then just rename your backup saves to the original Provenance save you've made at the start. (Copy a filename, delete this save state, then rename your backup save state). That worked for me, I hope it will help somebody.

**Comment by JoeMatt** [comment]
@L1ebermann Thank for the in-depth info.

We have a new wiki at https://wiki.provenance-emu.com that is user contributable with markdown. You can copy/paste your response into a pull request on that page would be really helpful!

**Comment by sevdestruct** [comment]
@L1ebermann you could add this to the Restoring Files section of wiki> https://wiki.provenance-emu.com/info/miscellaneous/restoring-files

**Comment by Meolax** [comment]
@JoeMatt, could you please reopen issue?

Still doesn't work on version 2.1.1.

Device info:
* ipad
* iPadOS 15.6.1

App info:
* version 2.1.1.
* source official github
* installed via altstore

**Comment by Meolax** [comment]
> Hey, dude. I also lost my saves a week ago, but I found a way to recover my saves, and I have a solution for this trouble. I don't speak english well, but I'll try to explain.
> 
> First, you need to download your save stats to your PC. I noticed that actual name of these files change when you download it, because Windows changes file name according to its standarts. Example:
> 
> ![Screenshot_2](https://user-images.githubusercontent.com/50751114/57949301-afe2c480-78ec-11e9-9676-ff8b70255f57.png)
> 
> Then, what I did is cleaned all save states I had in folder Iphone\Save states[%Game]. Delete the game from Provenance and install it again. Now you are going to your game, and do ONE save state. Then you are going to your save state folder and see 2 files: one containing .png and the other one is .svs; What you do now is : COPY both .svs and .png files from your PC with matching numbers:
> 
> ![Untitled](https://user-images.githubusercontent.com/50751114/57949581-81b1b480-78ed-11e9-8171-b91125bea9e0.png)
> 
> Then just rename your backup saves to the original Provenance save you've made at the start. (Copy a filename, delete this save state, then rename your backup save state). That worked for me, I hope it will help somebody.

So, in my case I just create new save rename old with name of new and replace it in save states directory.

I suppose something goes wrong in Refresh Game Library.
