### ISSUE TITLE
Virtual DualShock game pad for PSX/PS1 emulator.

### ISSUE THREAD

**Issue by felipedilho** [Provenance-Emu/Provenance#1210]
I wish there was a way to play games such as Ape Escape using only my iPhone, it would be much more practical, my request is also related with my inability to make my PS4 controller analog sticks to work, and also by being unable to find solutions to this online, I tried to use the commands L1+L2+R1+R2+Circle or L1+L2+R1+R2+Cross but neither one of them seem to enable the analog sticks, not by pressing all at the same time and not by pressing them in sequence.

 

Ideally I would like to not have to use a controller to play games that require analog sticks, sometimes I have some free time after lunch in my university and would appreciate not having to bring a controller with me to be able to play. I don't think that it would be so difficult to make two virtual analog controls in a GUI to implement this, other emulators such as the PS2 emulator play! have those controls available, for example.   

#
 

although not preferential, if I at least were able to make my PS4 controller work properly I would already be happy.

#
 

the experimental PS2 play! emulator GUI:
![Play-PS2-Emulator](https://user-images.githubusercontent.com/56373867/66533896-e4009100-eaea-11e9-8af1-46c18f856352.png)

**Comment by sevdestruct** [comment]
- Duplicate. Virtual sticks already in #718 
- R3/L3 should already implemented in app touch buttons.  #1069  fixed in da778aa
- PS and Xbox controllers will be reviewed separately, but have been reported to be working already. L3/R3 via those should already be working in latest build along MFi support. also addressed in da778aa

_**Please unpack isolated requests into separate items and search the Issues first.**_

Use the Discord server for #help
