### ISSUE TITLE
All games disappeared

### ISSUE THREAD

**Issue by therangerangler** [Provenance-Emu/Provenance#1316]
replaceWithSummaryOrDelete

 
### Expected: 

replaceWithExpectedResults

 
### Actual: 

replaceWithActualResults

 ### Reproduce:  

1. replaceWithSteps
2. 
3. 

# 
#### NOTES  

replaceWithNotesOrDelete

#

#### APP VERSION
- [x] 1.5 *beta*
- [ ] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [x] [Side-Loading](https://git.io/vpYzf)
- [x] [Building](https://git.io/vpYzv) *from Source*

#### PLATFORM
- [ ] iPhone
- [ ] iPad
- [x] Apple TV

#### iOS/tvOS VERSION
- [x] 12.x
- [ ] 11.x
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by therangerangler** [comment]
Fired up provenance, all games disappeared.  I try to re-import them and they never appear in the library.  Guessing there was an Apple TV update, any ideas?

**Comment by sevdestruct** [comment]
It's probaby…I believe Apple TV stores all these in a temporary cache unfortunately, so if you are downloading content elsewhere like videos and such it may dump what you have as stored for roms, may help if you can keep to streaming services that may not push out your roms on that device. If it isn't this…  try re-installing latest build and otherwise jump on Discord to see if someone can help you sort it out.
