### ISSUE TITLE
Reduce installation package size

### ISSUE THREAD

**Issue by nenge123** [Provenance-Emu/Provenance#1435]
1.5beta encountered the following problems in Ios14. 

- importing PS1 neogeo game will not generate game list, and manual movement will completely paralyze apple's [file management] application. 

- mednafen core can't be used at all. Even if bios is ready, I hope to remove it and reduce the size of installation package.

- I hope the user can choose whether to load the game cover or not. One of my game files shows wrong pictures and titles.
#### APP VERSION
- [x] 1.5 *beta*
#### PLATFORM
- iPhone

#### iOS/tvOS VERSION
- 14

**Comment by JoeMatt** [comment]
Not gonna happen.

We can't selectively distribute cores like OpenEMU, since we need to code sign all at install time.

Also these issues sound specific to a particular build, no one else is reporting simular issues.

Finally, you can add your own artwork, so there's no reason to disable the auto artwork adding since a majority of users would prefer that.
