### ISSUE TITLE
tvOS build failed: "the linked and embedded framework 'Realm.framework' was built for tvOS and tvOS simulator"

### ISSUE THREAD

**Issue by sporritt** [Provenance-Emu/Provenance#1518]
With a fresh checkout of the `master` branch, on XCode 12.5, using the `ProvenanceTV-Release` target deploying directly to an Apple TV 4K,  the build fails with this message:

`Building for tvOS, but the linked and embedded framework 'Realm.framework' was built for tvOS and tvOS simulator`

I have followed the steps in the getting started guide related to changing package name, setting up signing etc.

 
### Expected: 

I thought the app would build and get deployed to my Apple TV

 
### Actual: 

XCode mocked me with an error message 

 ### Reproduce:  

1. Checkout `master`
2. Replace the package name as detailed in the guide
3. Setup signing
4. Choose `ProvenanceTV-Release` and an Apple TV 4k as target
5. Build 

# 
#### APP VERSION
- [ ] 1.5 *beta*
- [x] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [x] [Building](https://git.io/vpYzv) *from Source*

#### PLATFORM
- [ ] iPhone
- [ ] iPad
- [x] Apple TV

#### iOS/tvOS VERSION
- [x] 14.x
- [ ] 13.x
- [ ] 12.x
- [ ] 11.x
- [ ] 10.x

-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by mrjschulte** [comment]
You should check out Develop, master is pretty old and outdated at this point.
You will then run into another issue which is largely related to Xcode 12.5 requiring a shift to XCframeworks due to how newer Mac Hardware can now run on both ARM64 and X86_64 requiring a new type of framework to be built out. The previous "Fat" frameworks no longer support this requirement cleanly and Apple has motivated us to look at moving to Xcframeworks to fix this.

Follow https://github.com/Provenance-Emu/Provenance/issues/1527 for an attempt to refactor us to use XCframeworks.
