### ISSUE TITLE
Support for .pbp PS1 games

### ISSUE THREAD

**Issue by CorporalPig22** [Provenance-Emu/Provenance#1534]
Hi,
I'm kinda new to Provenance. I'm trying to compress my ROMs to save space on my phone, and that leads me to my question: Does Provenance support PS1 ROMs that are in a .pbp file, and if not, what's the best compression option for PS1 games supported by Provenance?

**Comment by JoeMatt** [comment]
We use Mednafen for PSX, and I don't think they support this format, 
https://mednafen.github.io/documentation/#Section_cd_images

**Comment by JoeMatt** [comment]
I looked into this some more,

PGP is a file format for Playstation portable. Some emulators do support this format, but there are issues there still such as not matching in the library since this format isn't hashed in any of the ROM databases.

I'm going to close this issue since I don't think we should really support a format that has such drawbacks for a heavy UI feature-rich app like Provenance.

**Comment by JoeMatt** [comment]
There's an outside chance we oculd match via serial numbers, but there's still more work that I'd want to do to support an obscure format. 
But if anyone runs across this issue, looks like this code is a good starting point, https://github.com/RobLoach/RetroArch/pull/7
