### ISSUE TITLE
Sega Saturn Support

### ISSUE THREAD

**Issue by jcvangent** [Provenance-Emu/Provenance#352]
Is it possible to add Sega Saturn support in Provenance? Or is that technically not possible with the hardware of the AppleTV4?

**Comment by jasarien** [comment]
I wouldn't say it's impossible. I looks like there other Saturn emulators out there for iOS, so the hardware should be capable. Might something to look into for the future.

**Comment by JoeMatt** [comment]
Provenance still doesn't have a way to deal with ISO, BIN+CUE rips. I believe that would be required for importing.

OpenEMU has experimental yabause support, which is a Sega Saturn emulator. I also believe that it supports ARMv7 and OpenGL ES 3.0 on Android, so it should be technically possible. 

I would personally wait for OpenEMU to consider their fork of yabause stable before trying to get Provenance to work. Plus the ISO issue.

**Comment by JoeMatt** [comment]
I've played around with a yabause branch located here, https://github.com/JoeMatt/Provenance/tree/yabause-Saturn

There is a compiler issue where it locks indefinitely compiling a file that includes compile-time generated source. If I can work out why that is, perhaps this could run. It's a fairly simple core beyond that bug.

Mednafen also has Saturn support but it's currently X86 only.

**Comment by yoshisuga** [comment]
I've been watching this repo, and I was able to compile this fork of yabause and build and run on iOS:
https://github.com/devmiyax/yabause

There was some C declaration missing, but i was able to compile the core using cmake and build and run the iOS binary.

Here's my fork with the fixes:
https://github.com/yoshisuga/yabause

There's instructions on how to build the core for iOS in `yabause/src/ios/CMakeLists.txt`.

The app itself has some integration with Google Firebase (just for ads, it looks like), and I had to create a firebase instance and generate a GoogleService-Info.plist to get it to run. The GoogleService-Info.plist file has to be placed in `yabause/serc/ios/uoyabause/`. 

I've never integrated a core in provenance but since we have the core library my guess is it wouldn't be that hard to integrate.

The core itsekf has pretty good performance and compatibility.

**Comment by tosh** [comment]
experimental support for Sega Saturn seems to be available (!) in Provenance 1.5 builds:

https://github.com/Provenance-Emu/Provenance/wiki/Supported-Systems

(just wanted to update this issue as I wasn't aware of this, please correct me if I am wrong)

**Comment by mrjschulte** [comment]
This is now done.
