### ISSUE TITLE
Missing Analog Input for games predating Dualshock joysticks

### ISSUE THREAD

**Issue by truckerai** [Provenance-Emu/Provenance#690]
First off, I want to thank you for all your hard work. I finally got the PSX emulator working on the AppleTV and my wife is currently enraptured by her childhood games. Best Valentines ever. 

Anyways, I bought the Steelseries Nimbus controller and the analog sticks aren't providing any form of directional input. I tried to use it on GBA and PSX games and neither one received input from the controllers. I didn't find any open or closed issues on the matter and wanted to see if this was working as expected or if I just drew the short straw. Any help on the matter would be greatly appreciated.

**Comment by jasarien** [comment]
Odd. I was playing PSX games just today and analogue input was definitely working with my Nimbus. I also played SNES and Genesis games using analogue controls too.

**Comment by truckerai** [comment]
What can I do to try and rectify the issue? Is there a log somewhere I can pull to show you? I don’t know hardly anything about how all this works.

**Comment by JoeMatt** [comment]
There's not really any logging of controls because it would flood the logs.
Unfortunately if you don't know enough to add print's and breakpoints to the source and run from Xcode to the device there's not a lot that can be done. As Jasarien said, not an issue other have seen and we've all been testing.

Make sure the controller is set to Player 1 in the settings, sometimes on Apple TV at least, it chooses the TV remote as Player 1 and the Nimbus ends up as player 2. I'd check that the controller is setup toe Player 1 first.

**Comment by jasarien** [comment]
I think I see @truckerai's issue -- it appears that games on PSX (as an example) that were released before the first analogue controller don't respond to the analogue sticks. An example is Tomb Raider 2. I can't remember if analogue controls were backwards compatible with games released before the dual shock. The original controller had a toggle button to enable/disable the analogue controls, and I think this button is also emulated in mednafen, but we have no UI to access it. Should we just hardcode it to always on, maybe?

**Comment by truckerai** [comment]
Sure thing. I might not be able to do it until tomorrow. My laptop was giving me grief so I’m doing a clean restore. I’ll try and wrap it up tonight so I can let you know tonight. 

On an unrelated note, is there anyway I can transfer roms to my Apple TV other than over the network than using the hotspot on my phone? My apartments network won’t let us use our own routers or see devices over the network. I used the hotspot on my phone initially, but it used all my data doing so.

**Comment by jasarien** [comment]
I’m not a 100% sure if it still works, but one of the early methods of transferring roms was using iTunes file sharing. Plug in your AppleTV into your Mac, load up iTunes and select your phone, and there should be some section for transferring files to apps that support it. I haven’t used it for years though, so like I said, I don’t know if its still there.

You could always just set up a private network with a router that isn’t connected to your apartments network — set it up with a hidden SSID and no-one would know. You could periodically connect your iPhone and AppleTV to your private network and transfer ROMs without having to blow away your data allowance.

**Comment by alexreid** [comment]
I think the best thing would be to add the P1/P2 Analog Buttons to the menu to allow the user to toggle them – as far as I know, games designed for the original, D-pad–only controller don’t work when the controller’s in analog mode, so forcing it on isn’t a viable solution. 

I’ve got a branch locally where I’ve hacked it in using the same approach as the start/select menu entries. I don’t really know Obj-C, Cocoa, or the Provenance codebase well, so it’s possible that I’m taking entirely the wrong approach, but I’m happy to open a PR for people to comment on if it’d be useful!

**Comment by sevdestruct** [comment]
Don't think this is unique to Nimbus..

**Comment by sevdestruct** [comment]
When the dualshock controller came out there was an analog button to enable this, can we not simulate it with a virtual toggle? If so, I can incorporate this into #718 or #725.

**Comment by alexreid** [comment]
Yep, that’s the approach I took to hacking it into my local copy – it simulates the Analog button on the controller being pressed and then released shortly after, in the same way that the Start/Select buttons work in the menu (when emulating PSX) in the current release.

**Comment by sevdestruct** [comment]
@alexreid, please submit a PR if you don't mind sharing that fix, so we can close this.

**Comment by JoeMatt** [comment]
You can do it in the menu, or there's a setting I can activate in Mednafen where you hold Start + Select + the 4 shoulder buttons for 1 second and it switches mode. That button combo is also configurable.

I have another branch where I was testing this, so it might end up on dev soon. The setting is ,
`psx.input.analog_mode_ct` and `psx.input.analog_mode_ct.compare` to change the buttons used to change mode, but we're  using too old version of Mednafen for the latter config. Time update Mednafen.

```
// Enable combo toggle
    MDFNI_SetSettingB("psx.input.analog_mode_ct", 1);
// Do this to emulate a button press from the original PSX toggle button
    [current didPushPSXButton:PVPSXButtonAnalogMode forPlayer:0];
```

**Comment by sevdestruct** [comment]
Cool. @JoeMatt Joe, maybe we combine something like this with #679? - might need the wait timer to hold a little longer if we implement anything I suggested in there so it doesnt trigger the Analog toggle when using for a button we don't have

**Comment by JoeMatt** [comment]
It doesn't need button combo support since it's built into Mednafen already. I could active the default combo as-is. The customise it would require updating Mednafen, which is overdue anyway but it's not a simple update. A lot of the project structure has been changed so I have to re-do a lot of the sub-project. Mednafen is huge since it works on so many systems so it's a lot of files and compiler settings to get right. We also could start to add support for using it as the core for systems where it overlaps with others like sega, SNES etc. Too bad Github doesn't have 'depends on' 'blocked by' etc for tickets like Jira does.

**Comment by sevdestruct** [comment]
I realize that, I meant to consider if we implement #679, we might want to just make an adjustment, just keeping a connection between them so it isn't forgotten. 

(Agreed, a prereq feature would be super helpful. Funny, just thought exactly the same thing when submitting Update SNES9x Core issue, at least if we're diligent in the post # linking we have soemthing - trying my best)

**Comment by JoeMatt** [comment]
Another option would be something similar to the feature I already want to add of per-core settings, which is per-core menu buttons.

```swift
typealias MenuItemAction = () -> Void 
struct MenuItem {
 enum MenuItemType {
     case momentary
     case toggle(state:Bool)
 }
 let title : String
 mutating var type : MenuItemType
 let action : MenuItemAction
}
var coreMenuItems : [MenuItem] -> {
 return [
     MenuItemType(title: "Analog Mode", type: .toggle(false), action: { [weak self] in
        self.didPush(psxButton: .analogMode, forPlayer:0) 
        // Toggle state code if type is toggle} )
  ]
}()
```

**Comment by sevdestruct** [comment]
Or just tack this on to #725 (Pause Menu Redesign) where I've outlined or at least make mention of a more bespoke means of something similar, because the Pause Menu Action Sheet is getting overloaded, but adding to it would be the first step before I get that designed.

As for Sega there is also this that needs further research/looking into.. well shit I can't remember the ticket so I'll link it later, but jasarien was saying he thought there was possibly a core-side means to detect which games require 3x button controller or 6x button controller…or worst-case-scenario a hard coded list), but that's moreso for determining which overlay to show not to waste a bunch of screen equity (and something I need to get straight for the Overlay Overhaul (#718))

Oh I remember it's related to this bug: #376.

**Comment by JoeMatt** [comment]
Well this is a feature of it's own, I would relate it to but not directly tack it into #725 since it's a specific code feature to provide the data objects whether or not it comes before or after #725 is irrelevant since it could be added to the current menu fairly easily.

6 button games apparently can be detected, if you look at `GenPlusGameCore.m` in OpenEMU they have a way of detecting by looking at the game ROM header and also an override list `pad6Buttons` for broken roms.

**Comment by sevdestruct** [comment]
Analog has been restored, and @dybuk's addition to his fix now allows analog input to input dpad if analog mode is off, so this is essentially implemented (at least the original feature request in this.
