### ISSUE TITLE
[Issue] Saves / loads not working (ios)

### ISSUE THREAD

**Issue by davidrozen** [Provenance-Emu/Provenance#792]
Everything is working fine appart of game saves / loads which is pretty huge.
I tried on different roms, same. 
It does not save anything when i click on it.
Im playing on the last 1.5 version of provenance. (On iphone X device, ios 11.2.6)
Thanks, any help is welcomed

**Comment by jasarien** [comment]
This is fixed in the latest develop. Where do you get the version of Provenance that you’re using? Unless you built from our source using our instructions: https://github.com/Provenance-Emu/Provenance/wiki/Installing-Provenance then we can’t help you.

It sounds to me like you’ve downloaded Provenance from some 3rd party site — if this is true, then we can’t guarantee that they didn’t build a buggy version. We also cannot know whether they’ve tampered with the app and included advertising or other unwanted modifications.

My suggestion would be to delete whatever build you’re using and re-install from our source, using the instructions linked above.

**Comment by davidrozen** [comment]
I got it on pandahelper, not sure if its the last one.
Oh i see, can i get the last build without using cydia impactor or so ? (Cause its not working for me).
Thx

**Comment by jasarien** [comment]
Read the instructions.

**Comment by sevdestruct** [comment]
We don't support whatever the f pandahelper is. Please delete it and boycott their distribution, we do not approve.
