### ISSUE TITLE
iPhone X menu / shoulder buttons too close to screen edge (causing mistaps based on edge of device proximity)

### ISSUE THREAD

**Issue by davidrozen** [Provenance-Emu/Provenance#793]
Hello, thanks to you guys i fix my save/load problems but now im having an issue, mainly concerly the menu button, which is almost unclickable sometimes.
Is there any other buttons skins / editing ? 
Thanks in advance !

**Comment by sevdestruct** [comment]
nah, no additional themes and maybe not for a while - but i'm aware of that button, it's funny because it's same size button as the shoudlers (which i might increase a little too (keep in mind the tap area is larger than the visual) but i know what is happenign for me on my iPhone X is similar, iut's really because we are used to a different distance from the edge, so i tend to like you tap technically right below the button instead of right on it. but would be fine on say my iphone 6.. Looking to fix this since the distance from edge is sthe same on both, but the distance of that edge of screen to edge of iPhone X is much shorter than it was on oilder models, throwing us off. 

i'll probably make a hack to detect the for iPhone X (hack because there isnt really a direct way to do that by apple) and move the current shoulders and menu down, but I was planning on moving them anyways, so… yeah.

**Comment by JoeMatt** [comment]
It's pretty easy to change the hit area of the buttons,

https://stackoverflow.com/a/32002161/4843032

Though instead of using an extension on UIButton, I would make it a protocol and then add a default implimention of that protocol. Then any button that needs an expanded hit detection area would just need to provide a CGSize of width and height to expand by and the protocol would take care of the rest. I can write this up pretty quickly, you guys can tweak the width / height as you want.

**Comment by davidrozen** [comment]
Ok thank you, that would be awesome
Yu-gi-oh forbidden memories would be a bit better :D 
By the way i don't know if it's from the github or a modified version of it but on the third party site "pandahelper", the skin of the buttons/ the way they are put is not bad, if you could check it out.

**Comment by sevdestruct** [comment]
Sorry…but what the fuck is pandahelper? We don't support any of that. And our version of 1.5 is the 1 and only official version, the origin source. Please do not use or support 3rd party distribution of our source code, it just makes our lives more difficult. Saves and Loads are fixed in the most recent 1.5 branch. So whatever build you have is bootleg.

**Comment by davidrozen** [comment]
Yeah you'r right ofc but where can i get the 1.5 skin version in here ?

**Comment by jasarien** [comment]
https://github.com/Provenance-Emu/Provenance/wiki/Installing-Provenance

**Comment by davidrozen** [comment]
I'm having an issue, can't install Xcode on my mac running on Mac OS sierra 10.12.6 
Any alternatives ? 
I can use a PC do to that instead ?

**Comment by jasarien** [comment]
Nope, Xcode only runs on a Mac. You need high sierra to run the latest Xcode. This is off topic, there are other resources for help with installing Xcode.

**Comment by sevdestruct** [comment]
this has been fixed, but not QA tested in the core-reicast feature branch

**Comment by sevdestruct** [comment]
menu button is now fixed to have an extended hit area beyond it's button visual, so it's easier to hit it now, even with the proximity to device edge on iphone X throwing us off -- as for shoulders, i am doing somethign else for those as a part of the preliminary 1.5 edition of #718 (which was meant for 2.0)
