### ISSUE TITLE
DELETED

### ISSUE THREAD

**Issue by Jamse22** [Provenance-Emu/Provenance#825]
Edit:

## Dreamcast Support
- [ ] Core integration… and a lot more.

#
this is my favorite platform I really want to play Sonic Adventure 2

**Comment by JoeMatt** [comment]
Code it yourself or shut the fuck up.

**Comment by sevdestruct** [comment]
(Re-opening this, since we didn't have a Core Additions listing or ticket for this…sorry, Joe — but he's right, don't just tell us what your favorite stuff is and expect someone to do it for you. There is ways to ask for support and features and that isn't it.) So, no promises. There is work on this started, maybe liucrative, maybe not, via REicast but @JoeMatt has reported it to be far from complete as an emulator core prior to integration attempts.

**Comment by JoeMatt** [comment]
There was #48
