### ISSUE TITLE
8bitdo/iCade not working correctly with N64

### ISSUE THREAD

**Issue by rwalkz** [Provenance-Emu/Provenance#849]
## Version of Provenance and how you installed/where you installed from

Xcode version (if you're building from source):

iOS version:

**Comment by sevdestruct** [comment]
WTF. this has no information. there is also a ticket open fro icade already: #741

**Comment by jasarien** [comment]
He wrote inside the html commment, so it was hidden 🤦‍♂️

**Comment by franky-supero** [comment]
The Vigilante 8 2nd offence works cine on Provenance 1.4 with or w/out controller. But in the 1.5 version the character goes nuts (it just kept on turning [left] to infinity) no physical controller connected or bluetooth is off, same goes with the same vigilante rom but different rom format downloaded. But the Controller works All fine on other PSX roms.

Same goes with the N64 D-pad does not work, for navigation. Only jump a b start etc... works.

**Comment by sevdestruct** [comment]
@franky-supero this issue is closed - the psx always turning left issue you are having has been fixed and was reeported here #1012 update to latest beta as for the OP, pretty sure that has been fixed in the remapping work. Keeping closed until a recent test on latest can be conducted regarding the original issue.
