### ISSUE TITLE
Mednafen: GameBoy* Button Mismaps

### ISSUE THREAD

**Issue by sevdestruct** [Provenance-Emu/Provenance#864]
Controller button mismaps. mostly revealed in the exposure of mednafen core to the shared systems.

Systems (+ core) effected:
- [ ] Game Boy (mednafen)
- [ ] Game Boy Color (mednafen)
- [ ] Game Boy Advance (mednafen)
- [ ] (more to come)

### Expected:  
A is A, B is B…

### Actual:  
A is B, B is A

# 
#### NOTES  
It's getting difficult to keep all the systems straight—need something visual. I am thinking to start making a doc that maps all this down, as a solid shared reference, moving forward.

#

#### APP VERSION
- [x] 1.5 *beta*
  - [x] latest build <sub><sup>*(as of writing)*</sup></sub>
- [ ] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [x] [Building](https://git.io/vpYzv) *from Source*
  - [x] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*

#### PLATFORM
- [x] iPhone
- [x] iPad
- [x] Apple TV

#### iOS/tvOS VERSION
- [x] Latest (11.3)
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Offiical Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by JoeMatt** [comment]
Aren't they mapped the way the original systems were? If B - A was the layout, that's how it should be layed out on MFi, despite how MFi has their buttons labeled, which is merely a common coincidence. It could be hieroglyphs for all it matters.

**Comment by sevdestruct** [comment]
I think this is actually touch controls, I was bringing from discord convo

**Comment by sevdestruct** [comment]
Maybe they can clarify. If it's about names not marchign. Haha who cares, 0ositikns matter. I actually want to rub the lanes off my nimbus and my gamevice

**Comment by jsex** [comment]
@JoeMatt Yes you're correct they're layout as the original systems were but it's not being based on mfi controllers as I found out about this during trying out the normal non color core for the gameboy without an mfi controller connected. Meaning it was acting like an mfi controller was connected by thinking b is a and a is b. It seems like mfi controllers like the design of the ps4 controller where a is the x button on the ps4 and circle is b where mfi has b as well so with the software keys where the a is on an mfi controller is where the b will be and the app is using a as b because of that (my controller was off as if it was on I wouldn't get the software keys) but this only happens to a specific core meaning its a bug as the other ones aren't having the same issue. I hope that wasn't as confusing as it seems but I will try out more cores for other systems and see what happens

**Comment by jsex** [comment]
add gba mednafen with a b issue as well and I think so far the gameboy series are the only one having this issue as other mednafen for like nes and snes work fine
