### ISSUE TITLE
Steelseries stratus, unable to start some games.

### ISSUE THREAD

**Issue by icpgithub** [Provenance-Emu/Provenance#926]
Hi, I'm using the steelseries stratus gamepad on the appletv 1.4 version, and some games can't be started whatever button I press.

### Expected:  
Start the game.

### Actual:  
Some games can't be started.

Some genesis or snes games are opened, i.e. Ghouls n ghosts (genesis) or super ghouls n ghosts (SNES), and when I must select "start", it can't be done, no matter what button I press. I've tried with other roms from games that doesn't work and it's the same issue. But if there's a menu in the game before starting, i.e. with an options menu for the game, I can't go up and down on it. but I can't start it.

### Reproduce:  

1. I open the game and it runs.
2. It gets to the menu game and when "press start", no matter what button I press, it doesn't.
3. Goes into demo and loop back.

#

#### APP VERSION
- [ ] 1.5 *beta*
  - [ ] latest build <sub><sup>*(as of writing)*</sup></sub>
- [x] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [x] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*
  - [ ] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*

#### PLATFORM
- [ ] iPhone
- [ ] iPad
- [x] Apple TV

#### iOS/tvOS VERSION
- [x] Latest (11.3)
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by tomp8628** [comment]
Can you push the Menu button on the controller? And if so, does Player 1 Start and Player 1 Select shownas options?

**Comment by icpgithub** [comment]
Yes, the menu is displayed when I push the menu button on the controller.

Only P2 start and P2 select is displayed. In other games that work, the same options are displayed.

**Comment by icpgithub** [comment]
Yes, it is registered as Player 1 :)

**Comment by tomp8628** [comment]
Well, unfortunately 1.4 is a release and there will not be any patches or fixes for it, since 1.5 is in beta testing and release prep.  Just make sure in controller settings icade is off or None is checked, forget exactly what it is.  When you hit menu on the controller in the game, scroll all the way up and down to make sure you are not missing the Player 1 Start/Select option.  If you have the remote registered as Player 2, either pick none for that or try clicking a button on the remote to for Start/Select.  Could also try updating the firmware on the controller, or looking for a new rom source. And watch what buttons you are first pressing to try for Start, sometimes on older systems a button would actually trigger the demo sequence.

**Comment by jasarien** [comment]
I believe this has been addressed for 1.5.

If you could test with a 1.5 build (instructions are on the Wiki) and let us know if you still have this problem, that’d be useful. Until then I’ll close this issue — feel free to reopen it if you find 1.5 still has the issue.

**Comment by icpgithub** [comment]
I tried to set the remote to none and still didn't work. I'll gladly test the 1.5 build, but I can't find an ipa to sideload and I can't use xcode to build it (I'm not a developer :(  )
