### ISSUE TITLE
Update the app to make it compatible to IOS 12

### ISSUE THREAD

**Issue by Cloutdaddyy** [Provenance-Emu/Provenance#937]
So if you didn't hear IOS 12 was announced and with that the first beta was released and I decided to give IOS 12 a shot and boy o boy we have a problem Provenance doesn't want to open anymore because IOS 12 doesn't support it i'm downgrading my phone back to IOS 11.4.1 at this moment but if i where you i think you should make it compatible before you get more issues like this.

**Comment by jasarien** [comment]
You gave us... 2 hours? You think we can just support a whole new iOS release in 2 hours? Stop using betas and expecting stuff to work immediately.

**Comment by sevdestruct** [comment]
The only problem here is that iOS 12 did not 'release'. It was announced and made available to developers as beta. If I were you I'd wise up and learn not to install beta OS on your only or main device (or only partition, because same advice goes for a computer). This is a never a good idea and just not good practice. 

That said, there is no reasonable expectation for a small unpaid open source team which has no production budget to support a beta OS, especially to have support within 2 hours of announcement.  We don't have commercial release schedules that need to match Apple's OS releases as we are not a commercial app and are not distributed through the app store.
